let
    Source = Csv.Document(File.Contents("C:\Users\YourName\vehicle_sales_clean.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
        {"Date", type date},
        {"Sales", type number},
        {"Profit", type number},
        {"Quantity", Int64.Type}
    })
in
    ChangedTypes
